# Generated by Django 5.0.1 on 2024-01-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Продукт')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('date_created', models.DateField(verbose_name='Дата Выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('company_type', models.CharField(choices=[('0', 'Завод'), ('1', 'Индивидуальный предприниматель'), ('2', 'Розничная сеть')], verbose_name='Тип компании')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('number_house', models.IntegerField(verbose_name='Номер дома')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень иерархии')),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name='Время создания')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Задолежность перед поставщиком')),
                ('parent_supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_suppliers', to='electro_net.supplier', verbose_name='Поставщик')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='electro_net.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
